### ISSUE TITLE
Improve KMM

### ISSUE THREAD

**Issue by xukai92** [JuliaEarth/DensityRatioEstimation.jl#20] opened 2019-12-31 00:10 UTC
Just a note for myself, the current impl. of KMM needs some work to get the following functionality back
- [ ] Automatic setting `σ` as the median of pairwise distances if not provided
- [ ] Dealing with matrix data
- [ ] GPU compatibility
- [ ] Dealing with an array of `σ`s

**Comment by xukai92** [comment] 2019-12-31 00:11
Just a reminder for myself.

**Comment by juliohm** [comment] 2019-12-31 00:38
Regarding (2) what would you like to do with matrices? It is not clear to me from the description. Regarding (3), you mean a hyperparameter tuning algorithm? Please make sure that KMM is equipped with a tuning strategy. I don't remember seeing one in the papers. Regarding (4), I think we shouldn't set default parameters for users, the decision is quite arbitrary. Let users take the median or do something more sophisticated if they need.

**Comment by xukai92** [comment] 2019-12-31 08:48
> Regarding (2) what would you like to do with matrices? It is not clear to me from the description. 

Just a fallback methods of KMM for pre-allocated Julia matrices.

> Regarding (3), you mean a hyperparameter tuning algorithm? Please make sure that KMM is equipped with a tuning strategy. I don't remember seeing one in the papers. 

An array of `σ`s corresponds to a sum of several RBF kernels. Those kernel computation can share the same pairwise distance computation.

> Regarding (4), I think we shouldn't set default parameters for users, the decision is quite arbitrary. Let users take the median or do something more sophisticated if they need.

First of all, this default choice is mentioned in Sugiyama's book. Second, users have to compute the pairwise distances matrices to pick the median value and this computation will be not re-used when calling the KMM ratio estimation function.

**Comment by juliohm** [comment] 2019-12-31 09:51
> Just a fallback methods of KMM for pre-allocated Julia matrices.
>
We need to brainstorm this further. Which interface are you proposing?
Currently we only support finite collections of samples in a way that
x_nu[i] is the i-th sample. Anything that deviates from this interface
requires additional design.

> An array of σs corresponds to a sum of several RBF kernels. Those kernel
> computation can share the same pairwise distance computation.
>
Unless this computation is used internally in the kmm/Julia.jl
implementation for example, I can only see it as a preprocessing step. Can
you elaborate on this? The previous code you had as far as I remember only
called the estimator with the median sigma.

> First of all, this default choice is mentioned in Sugiyama's book. Second,
> users have to compute the pairwise distances matrices to pick the median
> value and this computation will be not re-used when calling the KMM ratio
> estimation function.
>
Yes it is mentioned in the book as a common practice but KMM does not have
a formal tuning strategy. It is just a heuristic. Regarding the reuse of
the distance calculations I don't see this as an issue because for example
users may be interested in computing this median differently with external
knowledge. Furthermore, this computation is done once just to find out
which estimator to call at the end with the data. The only way I see for
including this default is via a new fitter method for KMM that mimics the
LCV for KLIEP. A code refactoring would be needed. Please let's discuss
this more before committing to coding.

**Comment by xukai92** [comment] 2019-12-31 13:53
> We need to brainstorm this further. Which interface are you proposing?
Currently we only support finite collections of samples in a way that
x_nu[i] is the i-th sample. Anything that deviates from this interface
requires additional design.

I don't think we need much change to the interface. What I want to support is `x_nu::AbstractMatrix` where `x_nu[:,i]` is the i-th sample. I only need to update `n_nu = last(size(x_nu))` and implement `gaussian_gramian` for `AbstractMatrix` as well.

> Unless this computation is used internally in the kmm/Julia.jl
implementation for example, I can only see it as a preprocessing step. Can
you elaborate on this?

It's internal. Basically I want to reuse the pairwise distance matrices; see
https://github.com/xukai92/DensityRatioEstimation.jl/blob/df2b50fa7f2c2cd1e62c29b86ef8c081539269db/src/moment_matching.jl#L55

> It is just a heuristic. Regarding the reuse of
the distance calculations I don't see this as an issue because for example
users may be interested in computing this median differently with external
knowledge.

Yes it is just a heuristic. But it's a more reasonable default than `1.0`, which can easilly fail in a lot of cases.

**Comment by xukai92** [comment] 2019-12-31 13:53
> Furthermore, this computation is done once just to find out
which estimator to call at the end with the data.

Can you explain more on this?

**Comment by juliohm** [comment] 2019-12-31 14:00
> I don't think we need much change to the interface. What I want to support is `x_nu::AbstractMatrix` where `x_nu[:,i]` is the i-th sample. I only need to update `n_nu = last(size(x_nu))` and implement `gaussian_gramian` for `AbstractMatrix` as well.

Check this entire thread on Discourse where I was suggesting a more general interface to finite collections: https://discourse.julialang.org/t/what-is-the-agreed-abstraction-for-the-size-of-finite-collections/32757 The issue is more profound, and we need to design carefully how to handle different layouts like dataframes, arrays, etc meanwhile that the `length` function doesn't work everywhere.

> It's internal. Basically I want to reuse the pairwise distance matrices; see
> https://github.com/xukai92/DensityRatioEstimation.jl/blob/df2b50fa7f2c2cd1e62c29b86ef8c081539269db/src/moment_matching.jl#L55

Exactly. This seems to be a preprocessing step with precomputed gramian matrices. We need a refactoring of the code to accommodate this if that is very much needed.

> Yes it is just a heuristic. But it's a more reasonable default than `1.0`, which can easilly fail in a lot of cases.

Fully agree. In that case we should consider eliminating the default `1.0` in the constructor of estimators. For KLIEP we can find the best sigma with LCV from a list of sigmas. We probably need a general fitter for both KMM and KLIEP that checks a bunch of sigmas.

> Can you explain more on this?

I understand that you are doing an ensemble of estimators and averaging the result. Perhaps we need an interface for ensemble estimators, that would be more general and reusable across estimators.

**Comment by juliohm** [comment] 2020-03-03 22:42
This issue contains many sub-issues that we should discuss separately. Let's close this one, and open a new one for (1) API for other types of data arrangements (matrices as opposed to iterable of samples), and (2) helper heuristic functions to set parameters such as sigma.

Issue (1) is more complex and we need to be clever to use the trait system in our favor. Issue (2) in my opinion is something that could live in user's script and not necessarily be included in this package for general use. If we decide to provide better heuristics for sigma and other parameters, we need to define a public API for finding these heuristic values.

**Closed by juliohm** 2020-03-03 22:42 UTC
